# Generated by Django 5.2.13 on 2026-04-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='connected_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='platforms.connectedaccount'),
        ),
    ]
